// ODBCBridge.h
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class odbcbridge_ODBCBridge */

#ifndef _Included_odbcbridge_ODBCBridge
#define _Included_odbcbridge_ODBCBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     odbcbridge_ODBCBridge
 * Method:    connect
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_odbcbridge_ODBCBridge_connect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     odbcbridge_ODBCBridge
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_odbcbridge_ODBCBridge_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     odbcbridge_ODBCBridge
 * Method:    listDatabases
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_odbcbridge_ODBCBridge_listDatabases
  (JNIEnv *, jobject);

/*
 * Class:     odbcbridge_ODBCBridge
 * Method:    listTables
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_odbcbridge_ODBCBridge_listTables
  (JNIEnv *, jobject, jlong);

/*
 * Class:     odbcbridge_ODBCBridge
 * Method:    listColumns
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_odbcbridge_ODBCBridge_listColumns
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     odbcbridge_ODBCBridge
 * Method:    query
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_odbcbridge_ODBCBridge_query
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     odbcbridge_ODBCBridge
 * Method:    fetchFields
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_odbcbridge_ODBCBridge_fetchFields
  (JNIEnv *, jobject, jlong);

/*
 * Class:     odbcbridge_ODBCBridge
 * Method:    fetchArray
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_odbcbridge_ODBCBridge_fetchArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     odbcbridge_ODBCBridge
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_odbcbridge_ODBCBridge_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
